### PR TITLE
Update API.md

### PR DESCRIPTION
**Pull request by thejones**
Path to https://hapijs.com/api/17.1.1#server.dependency()

### CODE REVIEW

**Comment by WesTyler** [comment]
https://hapijs.com/api#-serverdependencydependencies-after ?

none of the `#server.dependency()` links actually anchor to any section for me.

**Comment by csrl** [comment]
Weird.  The disconnect is that if you go to https://hapijs.com/api and click on the nav menu on the right, the anchor #server.dependency() is shown.  But if you navigate directly to that, it doesn't work.

Your final link does work for me, so let's go with that.

**Comment by WesTyler** [comment]
Ah, I see. That makes sense. :+1:

**Comment by csrl** [comment]
I'll hold off on merging this until we see what hapijs/hapijs.com#527 comes back with.

Also, please update your PR to a single commit with a relevant commit message.

**Comment by csrl** [comment]
I resolved this for now by making the hapi doc links generic until hapijs/hapijs.com#527 is dealt with.  Unless we can expect stable links, there isn't much point in providing them when they can go stale at any moment.

**Pull request closed without merging**
